name=readline
version=readline
types=gz 
tarball=readline-$(version).tar.$(ext)
#TODO: MD5 protection support

#One mirror per line
define mirrors
ftp://ftp.cwru.edu/pub/bash/
endef

receipe=autotools
autoreconf=no
